language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - composer phpcs
  - composer phpmd
  - composer phpcpd
  - composer test

after_script:
  - php vendor/bin/coveralls -v
